In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import warnings

In [2]:
df = pd.read_csv('../data/DataSet2.csv')
df.head(10)

,Unnamed: 0,Film,Oscar Year,Film Studio/Producer(s),Award,Year of Release,Movie Time,Movie Genre,IMDB Rating,IMDB Votes,...,Tomatometer Status,Tomatometer Rating,Tomatometer Count,Audience Status,Audience Rating,Audience Count,Tomatometer Top Critics Count,Tomatometer Fresh Critics Count,Tomatometer Rotten Critics Count,Film ID
0,0,Wings,1927/28,Famous Players-Lasky,Winner,1927,144,"Drama,Romance,War",7.5,"12,221",...,Certified-Fresh,93.0,46.0,Upright,78.0,3530.0,9.0,43.0,3.0,2becf7d5-a3de-46ab-ae45-abdd6b588067
1,1,7th Heaven,1927/28,Fox,Nominee,1927,110,"Drama,Romance",7.7,"3,439",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19ed3295-a878-4fd2-8e60-5cd7b5f93dad
2,2,The Racket,1927/28,The Caddo Company,Nominee,1928,84,"Crime,Drama,Film-Noir",6.7,"1,257",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3111c2d8-0908-4093-8ff3-99c89f2f2f08
3,3,The Broadway Melody,1928/29,Metro-Goldwyn-Mayer,Winner,1929,100,"Drama,Musical,Romance",5.7,"6,890",...,Rotten,33.0,24.0,Spilled,21.0,1813.0,7.0,8.0,16.0,de063f3f-2d35-4e1c-8636-6eb4c16bd236
4,4,Alibi,1928/29,Feature Productions,Nominee,1929,91,"Action,Crime,Romance",5.8,765,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,609887c2-877c-43a4-b88c-e40e31096a98
5,5,Hollywood Revue,1928/29,Metro-Goldwyn-Mayer,Nominee,1929,130,"Comedy,Music",5.7,"2,004",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,689f22d5-a700-4ce1-b9be-65652f32c186
6,6,In Old Arizona,1928/29,Fox,Nominee,1928,95,Western,5.6,"1,019",...,Rotten,56.0,9.0,Spilled,38.0,356.0,2.0,5.0,4.0,a0644f19-a136-44c2-ab5d-50978ef19608
7,7,The Patriot,1928/29,Paramount Famous Lasky,Nominee,1928,113,"Drama,History,Thriller",7.4,18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5d4ef7bd-2f81-47f3-9305-2c8fe140d4e4
8,8,All Quiet on the Western Front,1929/30,Universal,Winner,1930,152,"Drama,War",8.1,"59,214",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,281742f9-3b4e-480d-b704-c8c15de6b721
9,9,The Big House,1929/30,Cosmopolitan,Nominee,1930,87,"Crime,Drama,Thriller",7.1,"2,079",...,Fresh,75.0,8.0,Upright,69.0,323.0,0.0,6.0,2.0,297aa285-29d7-4a22-b833-c5632ab3e562

In [3]:
df.columns

Index(['Unnamed: 0', 'Film', 'Oscar Year', 'Film Studio/Producer(s)', 'Award',
       'Year of Release', 'Movie Time', 'Movie Genre', 'IMDB Rating',
       'IMDB Votes', 'Movie Info', 'Genres', 'Critic Consensus',
       'Content Rating', 'Directors', 'Authors', 'Actors',
       'Original Release Date', 'Streaming Release Date', 'Production Company',
       'Tomatometer Status', 'Tomatometer Rating', 'Tomatometer Count',
       'Audience Status', 'Audience Rating', 'Audience Count',
       'Tomatometer Top Critics Count', 'Tomatometer Fresh Critics Count',
       'Tomatometer Rotten Critics Count', 'Film ID'],
      dtype='object')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 571 entries, 0 to 570
Data columns (total 30 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Unnamed: 0                        571 non-null    int64
 1   Film                              571 non-null    object
 2   Oscar Year                        571 non-null    object
 3   Film Studio/Producer(s)           571 non-null    object
 4   Award                             571 non-null    object
 5   Year of Release                   571 non-null    int64
 6   Movie Time                        571 non-null    int64
 7   Movie Genre                       571 non-null    object
 8   IMDB Rating                       571 non-null    float64
 9   IMDB Votes                        571 non-null    object
 10  Movie Info                        438 non-null    object
 11  Genres                            439 non-null    object
 12  Critic Consensus                  339 non-null    object
 13  Content Rating                    439 non-null    object
 14  Directors                         437 non-null    object
 15  Authors                           437 non-null    object
 16  Actors                            439 non-null    object
 17  Original Release Date             439 non-null    object
 18  Streaming Release Date            438 non-null    object
 19  Production Company                439 non-null    object
 20  Tomatometer Status                439 non-null    object
 21  Tomatometer Rating                439 non-null    float64
 22  Tomatometer Count                 439 non-null    float64
 23  Audience Status                   436 non-null    object
 24  Audience Rating                   439 non-null    float64
 25  Audience Count                    439 non-null    float64
 26  Tomatometer Top Critics Count     439 non-null    float64
 27  Tomatometer Fresh Critics Count   439 non-null    float64
 28  Tomatometer Rotten Critics Count  439 non-null    float64
 29  Film ID                           571 non-null    object
dtypes: float64(8), int64(3), object(19)
memory usage: 134.0+ KB

### Обработка пропущенных знаечний

Посмотрим число пропущенных значений

In [5]:
df.isna().sum()

Unnamed: 0                            0
Film                                  0
Oscar Year                            0
Film Studio/Producer(s)               0
Award                                 0
Year of Release                       0
Movie Time                            0
Movie Genre                           0
IMDB Rating                           0
IMDB Votes                            0
Movie Info                          133
Genres                              132
Critic Consensus                    232
Content Rating                      132
Directors                           134
Authors                             134
Actors                              132
Original Release Date               132
Streaming Release Date              133
Production Company                  132
Tomatometer Status                  132
Tomatometer Rating                  132
Tomatometer Count                   132
Audience Status                     135
Audience Rating                     132
Audience Count                      132
Tomatometer Top Critics Count       132
Tomatometer Fresh Critics Count     132
Tomatometer Rotten Critics Count    132
Film ID                               0
dtype: int64

Из данного списка видно, что из 571 фильма, представленного в датасете, у 132 фильмов отсутствует информация в 19 столбцах из 30. Удалим эти фильмы из таблицы, потому что восстановить данные этих столбцов восстановить невозможно, а подставление нулей или медианы очень сильно скажется на оценке содержимого.

In [6]:
df.dropna(subset=['Production Company'], how='all', inplace=True)

In [7]:
df.isna().sum()

Unnamed: 0                            0
Film                                  0
Oscar Year                            0
Film Studio/Producer(s)               0
Award                                 0
Year of Release                       0
Movie Time                            0
Movie Genre                           0
IMDB Rating                           0
IMDB Votes                            0
Movie Info                            1
Genres                                0
Critic Consensus                    100
Content Rating                        0
Directors                             2
Authors                               2
Actors                                0
Original Release Date                 0
Streaming Release Date                1
Production Company                    0
Tomatometer Status                    0
Tomatometer Rating                    0
Tomatometer Count                     0
Audience Status                       3
Audience Rating                       0
Audience Count                        0
Tomatometer Top Critics Count         0
Tomatometer Fresh Critics Count       0
Tomatometer Rotten Critics Count      0
Film ID                               0
dtype: int64

В столбце "Critic Consensus" проставим unknown, потому что восстановить его невозможно, это же сделаем со столбцами "Movie Info", "Directors", "Authors"

In [8]:
df['Critic Consensus'] = df['Critic Consensus'].fillna('Unknown')
df['Movie Info'] = df['Movie Info'].fillna('Unknown')
df['Directors'] = df['Directors'].fillna('Unknown')
df['Authors'] = df['Authors'].fillna('Unknown')

In [9]:
df.isna().sum()

Unnamed: 0                          0
Film                                0
Oscar Year                          0
Film Studio/Producer(s)             0
Award                               0
Year of Release                     0
Movie Time                          0
Movie Genre                         0
IMDB Rating                         0
IMDB Votes                          0
Movie Info                          0
Genres                              0
Critic Consensus                    0
Content Rating                      0
Directors                           0
Authors                             0
Actors                              0
Original Release Date               0
Streaming Release Date              1
Production Company                  0
Tomatometer Status                  0
Tomatometer Rating                  0
Tomatometer Count                   0
Audience Status                     3
Audience Rating                     0
Audience Count                      0
Tomatometer Top Critics Count       0
Tomatometer Fresh Critics Count     0
Tomatometer Rotten Critics Count    0
Film ID                             0
dtype: int64

В столбце "Streaming Release Date"

In [10]:
df_new = df[df['Streaming Release Date'].isnull()]
df_new

,Unnamed: 0,Film,Oscar Year,Film Studio/Producer(s),Award,Year of Release,Movie Time,Movie Genre,IMDB Rating,IMDB Votes,...,Tomatometer Status,Tomatometer Rating,Tomatometer Count,Audience Status,Audience Rating,Audience Count,Tomatometer Top Critics Count,Tomatometer Fresh Critics Count,Tomatometer Rotten Critics Count,Film ID
212,212,Cat on a Hot Tin Roof,1958,Lawrence Weingarten,Nominee,1958,108,Drama,8.0,"47,222",...,Fresh,97.0,37.0,Upright,92.0,31748.0,5.0,36.0,1.0,466621aa-287c-4316-9083-74a5fc72a4f6

In [11]:
df.loc[df['Film'] == 'Cat on a Hot Tin Roof', 'Production Company']

212    MGM Home Entertainment
Name: Production Company, dtype: object

Посмотрим на дату онлайн релиза фильмов, которые имеют ту же компанию по продакшену

In [12]:
df.loc[df['Production Company'] == 'MGM Home Entertainment', 'Streaming Release Date']

3      2017-02-25
13     2017-01-08
18     2016-12-20
27     2012-04-16
60     2016-11-18
70     2015-12-26
72     2016-11-21
83     2009-01-01
84     2013-12-03
92     2015-09-11
106    2017-03-12
120    2017-01-12
126    2016-11-21
129    2016-05-07
146    2008-08-04
148    2008-12-31
154    2009-04-01
173    2012-04-16
182    2013-12-03
186    2008-01-01
193    2015-05-08
195    2017-01-19
210    2016-04-19
212           NaN
213    2017-04-18
214    2016-05-04
306    2016-07-14
359    2016-11-01
Name: Streaming Release Date, dtype: object

Мы видим, что даты онлайн релизов фильмов, стоящих рядом, находятся в 2016-2017 годах, проставим схлжую дату.

In [13]:
df.at [212, 'Streaming Release Date'] = '2016-08-10'

Так как столбец "Audience Status" содержит исключительно два значения "Upright" и "Spilled", то проставим вместо NaN самое часто встречающееся значение

In [14]:
df.mode()['Audience Status'][0]

'Upright'

In [15]:
df['Audience Status'] = df['Audience Status'].fillna('Upright')

In [16]:
df.isna().sum()

Unnamed: 0                          0
Film                                0
Oscar Year                          0
Film Studio/Producer(s)             0
Award                               0
Year of Release                     0
Movie Time                          0
Movie Genre                         0
IMDB Rating                         0
IMDB Votes                          0
Movie Info                          0
Genres                              0
Critic Consensus                    0
Content Rating                      0
Directors                           0
Authors                             0
Actors                              0
Original Release Date               0
Streaming Release Date              0
Production Company                  0
Tomatometer Status                  0
Tomatometer Rating                  0
Tomatometer Count                   0
Audience Status                     0
Audience Rating                     0
Audience Count                      0
Tomatometer Top Critics Count       0
Tomatometer Fresh Critics Count     0
Tomatometer Rotten Critics Count    0
Film ID                             0
dtype: int64

In [17]:
df

,Unnamed: 0,Film,Oscar Year,Film Studio/Producer(s),Award,Year of Release,Movie Time,Movie Genre,IMDB Rating,IMDB Votes,...,Tomatometer Status,Tomatometer Rating,Tomatometer Count,Audience Status,Audience Rating,Audience Count,Tomatometer Top Critics Count,Tomatometer Fresh Critics Count,Tomatometer Rotten Critics Count,Film ID
0,0,Wings,1927/28,Famous Players-Lasky,Winner,1927,144,"Drama,Romance,War",7.5,"12,221",...,Certified-Fresh,93.0,46.0,Upright,78.0,3530.0,9.0,43.0,3.0,2becf7d5-a3de-46ab-ae45-abdd6b588067
3,3,The Broadway Melody,1928/29,Metro-Goldwyn-Mayer,Winner,1929,100,"Drama,Musical,Romance",5.7,"6,890",...,Rotten,33.0,24.0,Spilled,21.0,1813.0,7.0,8.0,16.0,de063f3f-2d35-4e1c-8636-6eb4c16bd236
6,6,In Old Arizona,1928/29,Fox,Nominee,1928,95,Western,5.6,"1,019",...,Rotten,56.0,9.0,Spilled,38.0,356.0,2.0,5.0,4.0,a0644f19-a136-44c2-ab5d-50978ef19608
9,9,The Big House,1929/30,Cosmopolitan,Nominee,1930,87,"Crime,Drama,Thriller",7.1,"2,079",...,Fresh,75.0,8.0,Upright,69.0,323.0,0.0,6.0,2.0,297aa285-29d7-4a22-b833-c5632ab3e562
13,13,Cimarron,1930/31,RKO Radio,Winner,1931,123,"Drama,Western",5.9,"5,851",...,Rotten,50.0,24.0,Spilled,25.0,1514.0,6.0,12.0,12.0,db2683c0-128e-4b5c-858f-d9f18c2fb9b9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
552,552,A Star Is Born,2018,"Bill Gerber, Bradley Cooper, and Lynette Howel...",Nominee,2018,136,"Drama,Music,Romance",7.6,"354,157",...,Certified-Fresh,90.0,517.0,Upright,79.0,20442.0,62.0,466.0,52.0,a8a00610-8b95-4d5f-b95e-128b6a2853ea
553,553,Vice,2018,"Dede Gardner, Jeremy Kleiner, Adam McKay, and ...",Nominee,2018,132,"Biography,Comdey,Drama",7.2,"132,014",...,Fresh,65.0,359.0,Upright,60.0,5061.0,47.0,234.0,125.0,27048415-ff2e-427e-a4de-5d2898a0812d
557,557,The Irishman,2019,"Martin Scorsese, Robert De Niro, Jane Rosentha...",Nominee,2019,209,"Biography,Crime,Drama",7.8,"349,303",...,Certified-Fresh,96.0,439.0,Upright,86.0,1057.0,53.0,421.0,19.0,cf8fb1fa-1a2b-48bd-a241-c7e9d487c09d
559,559,Joker,2019,"Todd Phillips, Bradley Cooper, and Emma Tillin...",Nominee,2019,122,"Crime,Drama,Thriller",8.4,"1,056,051",...,Fresh,68.0,574.0,Upright,88.0,66303.0,56.0,393.0,182.0,9988cdef-854b-4e3d-8dc4-19e8e8717b9b
561,561,Marriage Story,2019,Noah Baumbach and David Heyman,Nominee,2019,137,"Comedy,Drama,Romance",7.9,"270,304",...,Certified-Fresh,94.0,381.0,Upright,85.0,184.0,48.0,359.0,22.0,4dfbadb9-b7f9-4c24-bbd8-5d55dce2c7c6

### Проверим уникальность значений

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 439 entries, 0 to 561
Data columns (total 30 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Unnamed: 0                        439 non-null    int64
 1   Film                              439 non-null    object
 2   Oscar Year                        439 non-null    object
 3   Film Studio/Producer(s)           439 non-null    object
 4   Award                             439 non-null    object
 5   Year of Release                   439 non-null    int64
 6   Movie Time                        439 non-null    int64
 7   Movie Genre                       439 non-null    object
 8   IMDB Rating                       439 non-null    float64
 9   IMDB Votes                        439 non-null    object
 10  Movie Info                        439 non-null    object
 11  Genres                            439 non-null    object
 12  Critic Consensus                  439 non-null    object
 13  Content Rating                    439 non-null    object
 14  Directors                         439 non-null    object
 15  Authors                           439 non-null    object
 16  Actors                            439 non-null    object
 17  Original Release Date             439 non-null    object
 18  Streaming Release Date            439 non-null    object
 19  Production Company                439 non-null    object
 20  Tomatometer Status                439 non-null    object
 21  Tomatometer Rating                439 non-null    float64
 22  Tomatometer Count                 439 non-null    float64
 23  Audience Status                   439 non-null    object
 24  Audience Rating                   439 non-null    float64
 25  Audience Count                    439 non-null    float64
 26  Tomatometer Top Critics Count     439 non-null    float64
 27  Tomatometer Fresh Critics Count   439 non-null    float64
 28  Tomatometer Rotten Critics Count  439 non-null    float64
 29  Film ID                           439 non-null    object
dtypes: float64(8), int64(3), object(19)
memory usage: 122.5+ KB

Проверим столбцы "Movie Genre", "Genres", "Content Rating", "Production Company", "Tomatometer Status", "Audience Status".

In [20]:
sorted(df['Movie Genre'].unique())

['Action,Adventure',
 'Action,Adventure,Drama',
 'Action,Adventure,Fantasy',
 'Action,Adventure,History',
 'Action,Adventure,Romance',
 'Action,Adventure,Sci-Fi',
 'Action,Biography,Crime',
 'Action,Crime,Drama',
 'Action,Drama,History',
 'Action,Drama,Thriller',
 'Action,Romance,Thriller',
 'Action,Sci-Fi,Thriller',
 'Adventure,Biography,Crime',
 'Adventure,Biography,Drama',
 'Adventure,Comedy,Crime',
 'Adventure,Comedy,Drama',
 'Adventure,Comedy,Family',
 'Adventure,Comedy,History',
 'Adventure,Comedy,Musical',
 'Adventure,Drama',
 'Adventure,Drama,Family',
 'Adventure,Drama,Fantasy',
 'Adventure,Drama,History',
 'Adventure,Drama,Romance',
 'Adventure,Drama,Sci-Fi',
 'Adventure,Drama,Thriller',
 'Adventure,Drama,War',
 'Adventure,Drama,Western',
 'Adventure,Family,Fantasy',
 'Adventure,Thriller',
 'Animation,Adventure,Comedy',
 'Animation,Family,Fantasy',
 'Biography,Comdey,Drama',
 'Biography,Comedy,Crime',
 'Biography,Comedy,Drama',
 'Biography,Crime,Drama',
 'Biography,Drama',
 'Biography,Drama,Family',
 'Biography,Drama,History',
 'Biography,Drama,Music',
 'Biography,Drama,Musical',
 'Biography,Drama,Romance',
 'Biography,Drama,Sport',
 'Biography,Drama,Thriller',
 'Biography,Drama,War',
 'Comedy,Crime,Drama',
 'Comedy,Crime,Musical',
 'Comedy,Crime,Mystery',
 'Comedy,Drama',
 'Comedy,Drama,Family',
 'Comedy,Drama,Fantasy',
 'Comedy,Drama,History',
 'Comedy,Drama,Music',
 'Comedy,Drama,Musical',
 'Comedy,Drama,Mystery',
 'Comedy,Drama,Romance',
 'Comedy,Drama,War',
 'Comedy,Family,Fantasy',
 'Comedy,Family,Musical',
 'Comedy,Fantasy,Music',
 'Comedy,Fantasy,Romance',
 'Comedy,Musical,Romance',
 'Comedy,Romance',
 'Comedy,Romance,War',
 'Comedy,War',
 'Crime,Drama',
 'Crime,Drama,Fantasy',
 'Crime,Drama,Film-Noir',
 'Crime,Drama,History',
 'Crime,Drama,Musical',
 'Crime,Drama,Mystery',
 'Crime,Drama,Romance',
 'Crime,Drama,Sci-Fi',
 'Crime,Drama,Thriller',
 'Crime,Film-Noir,Mystery',
 'Drama',
 'Drama,Family',
 'Drama,Family,Fantasy',
 'Drama,Family,Musical',
 'Drama,Family,Romance',
 'Drama,Family,Western',
 'Drama,Fantasy',
 'Drama,Fantasy,Romance',
 'Drama,Film-Noir',
 'Drama,History',
 'Drama,History,Musical',
 'Drama,History,Romance',
 'Drama,History,Sport',
 'Drama,History,Thriller',
 'Drama,Music',
 'Drama,Music,Musical',
 'Drama,Music,Romance',
 'Drama,Musical,Romance',
 'Drama,Mystery',
 'Drama,Mystery,Romance',
 'Drama,Mystery,Thriller',
 'Drama,Mystery,War',
 'Drama,Romance',
 'Drama,Romance,Sci-Fi',
 'Drama,Romance,War',
 'Drama,Sci-Fi',
 'Drama,Sci-Fi,Thriller',
 'Drama,Sport',
 'Drama,Thriller',
 'Drama,Thriller,Western',
 'Drama,War',
 'Drama,Western',
 'Film-Noir,Mystery,Thriller',
 'Horror',
 'Horror,Mystery,Thriller',
 'Western']

In [21]:
sorted(df['Genres'].unique())

['Action & Adventure',
 'Action & Adventure, Animation, Comedy, Kids & Family',
 'Action & Adventure, Art House & International, Classics, Drama',
 'Action & Adventure, Art House & International, Classics, Drama, Romance',
 'Action & Adventure, Classics',
 'Action & Adventure, Classics, Comedy, Kids & Family, Musical & Performing Arts, Science Fiction & Fantasy',
 'Action & Adventure, Classics, Comedy, Romance',
 'Action & Adventure, Classics, Drama',
 'Action & Adventure, Classics, Drama, Mystery & Suspense',
 'Action & Adventure, Classics, Drama, Mystery & Suspense, Romance',
 'Action & Adventure, Classics, Drama, Mystery & Suspense, Science Fiction & Fantasy',
 'Action & Adventure, Classics, Drama, Romance',
 'Action & Adventure, Classics, Drama, Science Fiction & Fantasy',
 'Action & Adventure, Classics, Drama, Western',
 'Action & Adventure, Classics, Romance',
 'Action & Adventure, Classics, Science Fiction & Fantasy',
 'Action & Adventure, Classics, Western',
 'Action & Adventure, Classics, Western, Romance',
 'Action & Adventure, Comedy, Drama, Kids & Family',
 'Action & Adventure, Comedy, Mystery & Suspense, Science Fiction & Fantasy',
 'Action & Adventure, Drama',
 'Action & Adventure, Drama, Kids & Family, Science Fiction & Fantasy',
 'Action & Adventure, Drama, Mystery & Suspense',
 'Action & Adventure, Drama, Mystery & Suspense, Science Fiction & Fantasy',
 'Action & Adventure, Drama, Science Fiction & Fantasy',
 'Action & Adventure, Drama, Western',
 'Action & Adventure, Science Fiction & Fantasy',
 'Animation, Comedy, Kids & Family',
 'Animation, Drama, Kids & Family, Musical & Performing Arts, Science Fiction & Fantasy, Romance',
 'Art House & International, Classics, Comedy, Drama, Romance',
 'Art House & International, Classics, Drama',
 'Art House & International, Drama',
 'Art House & International, Drama, Mystery & Suspense',
 'Art House & International, Drama, Romance',
 'Art House & International, Drama, Sports & Fitness',
 'Classics, Comedy',
 'Classics, Comedy, Drama',
 'Classics, Comedy, Drama, Kids & Family',
 'Classics, Comedy, Drama, Kids & Family, Musical & Performing Arts',
 'Classics, Comedy, Drama, Musical & Performing Arts',
 'Classics, Comedy, Drama, Musical & Performing Arts, Romance',
 'Classics, Comedy, Drama, Musical & Performing Arts, Western',
 'Classics, Comedy, Drama, Mystery & Suspense, Romance',
 'Classics, Comedy, Drama, Romance',
 'Classics, Comedy, Drama, Science Fiction & Fantasy, Romance',
 'Classics, Comedy, Kids & Family, Musical & Performing Arts, Science Fiction & Fantasy',
 'Classics, Comedy, Musical & Performing Arts',
 'Classics, Comedy, Musical & Performing Arts, Romance',
 'Classics, Comedy, Mystery & Suspense',
 'Classics, Comedy, Romance',
 'Classics, Comedy, Science Fiction & Fantasy, Romance',
 'Classics, Documentary, Drama',
 'Classics, Documentary, Drama, Romance',
 'Classics, Documentary, Musical & Performing Arts, Special Interest, Television',
 'Classics, Drama',
 'Classics, Drama, Faith & Spirituality',
 'Classics, Drama, Kids & Family',
 'Classics, Drama, Kids & Family, Musical & Performing Arts',
 'Classics, Drama, Kids & Family, Romance',
 'Classics, Drama, Kids & Family, Science Fiction & Fantasy',
 'Classics, Drama, Kids & Family, Science Fiction & Fantasy, Special Interest, Romance',
 'Classics, Drama, Musical & Performing Arts',
 'Classics, Drama, Musical & Performing Arts, Romance',
 'Classics, Drama, Mystery & Suspense',
 'Classics, Drama, Mystery & Suspense, Romance',
 'Classics, Drama, Mystery & Suspense, Science Fiction & Fantasy',
 'Classics, Drama, Romance',
 'Classics, Drama, Television, Romance',
 'Classics, Drama, Western',
 'Classics, Drama, Western, Romance',
 'Classics, Horror',
 'Classics, Kids & Family',
 'Classics, Kids & Family, Musical & Performing Arts, Science Fiction & Fantasy',
 'Classics, Musical & Performing Arts, Romance',
 'Classics, Western',
 'Comedy',
 'Comedy, Drama',
 'Comedy, Drama, Musical & Performing Arts',
 'Comedy, Drama, Mystery & Suspense',
 'Comedy, Drama, Mystery & Suspense, Science Fiction & Fantasy, Romance',
 'Comedy, Drama, Romance',
 'Comedy, Drama, Sports & Fitness',
 'Comedy, Musical & Performing Arts',
 'Comedy, Romance',
 'Comedy, Science Fiction & Fantasy, Romance, Sports & Fitness',
 'Cult Movies, Drama',
 'Drama',
 'Drama, Gay & Lesbian',
 'Drama, Kids & Family, Science Fiction & Fantasy, Sports & Fitness',
 'Drama, Musical & Performing Arts',
 'Drama, Musical & Performing Arts, Romance',
 'Drama, Mystery & Suspense',
 'Drama, Mystery & Suspense, Romance',
 'Drama, Mystery & Suspense, Science Fiction & Fantasy',
 'Drama, Romance',
 'Drama, Science Fiction & Fantasy',
 'Drama, Science Fiction & Fantasy, Romance',
 'Drama, Science Fiction & Fantasy, Special Interest, Romance',
 'Drama, Sports & Fitness',
 'Drama, Western',
 'Horror, Mystery & Suspense',
 'Kids & Family, Mystery & Suspense',
 'Musical & Performing Arts',
 'Musical & Performing Arts, Romance',
 'Mystery & Suspense',
 'Mystery & Suspense, Western',
 'Science Fiction & Fantasy']

In [22]:
sorted(df['Content Rating'].unique())

['G', 'NR', 'PG', 'PG-13', 'R']

In [23]:
sorted(df['Production Company'].unique())

['20th Century Fox',
 '20th Century Fox Film Corporation',
 '20th Century-Fox',
 '21 Laps Entertainment',
 'A24',
 'A24 Films',
 'Annapurna Pictures',
 'Batjac Productions',
 'Buena Vista',
 'Buena Vista Internationa',
 'Buena Vista Pictures',
 'Columbia',
 'Columbia Pictures',
 'Columbia Pictures Corporation',
 'Criterion Collection',
 'DreamWorks Studios',
 'Dreamworks',
 'Dreamworks Distribution',
 'Dreamworks Distribution LLC',
 'Dreamworks Pictures',
 'Eagle-Lion Films',
 'Element Pictures',
 'Embassy Pictures/Rialto Pictures',
 'Film 44',
 'Focus Features',
 'Fox',
 'Fox Searchlight',
 'Fox Searchlight Pictures',
 'Fox Searchlight Pictures, Film4 and Waypoint',
 'Gramercy',
 'Gramercy Pictures',
 'Gravitas',
 'HBO Video',
 'Hollywood/Buena Vista',
 'IFC Films',
 'Image Entertainment Inc.',
 'Liberty Films',
 'Liongate Films',
 'Lions Gate Films',
 'Lionsgate',
 'Live Home Video',
 'MCA Universal Home Video',
 'MGM',
 'MGM Home Entertainment',
 'MGM/United Artists',
 'Madacy Entertainment',
 'Marvel Studios',
 'Media Home Entertainment',
 'Miramax',
 'Miramax Films',
 'NCM Fathom',
 'Nelson Entertainment',
 'Netflix',
 'New Line Cinema',
 'New Line Home Entertainment',
 'Open Road Films',
 'Orion Pictures',
 'Orion Pictures Corporation',
 'Paramount',
 'Paramount Classics',
 'Paramount Home Video',
 'Paramount Pictures',
 'Paramount Studios',
 'Paramount Vantage',
 'RKO',
 'RKO Radio Pictures',
 'Republic Pictures',
 'Rialto Pictures',
 'Roadside Attractions',
 'Roadside Attractions\xa0',
 'Samuel Goldwyn Films',
 'See-Saw Films',
 'Slowhand Releasing',
 'Sony Classics',
 'Sony Pictures',
 'Sony Pictures Classics',
 'Sony Pictures Entertainment',
 'Sony Pictures Home Entertainment',
 'Sony Pictures/Screen Gems',
 'Strand Releasing',
 'Summit Entertainment',
 'The Weinstein Co.',
 'The Weinstein Co./MGM',
 'The Weinstein Company',
 'TriStar Pictures',
 'Turner Home Entertainment',
 'Twentieth Century Fox',
 'Twentieth Century Fox Home Entertainment',
 'USA Films',
 'United Artists',
 'United Artists Films',
 'Universal',
 'Universal Pictures',
 'Universal Studios',
 'Unknown',
 'WARNER BROTHERS PICTURES',
 'WB',
 'Walt Disney Pictures',
 'Walt Disney Productions',
 'Warner Bros.',
 'Warner Bros. Pictures',
 'Warner Brothers/Seven Arts',
 'Warner Home Video',
 'Woodfall Film Productions']

In [24]:
sorted(df['Tomatometer Status'].unique())

['Certified-Fresh', 'Fresh', 'Rotten']

In [25]:
sorted(df['Audience Status'].unique())

['Spilled', 'Upright']

Замены надо производить только в столбце "Production Company"

### Замена типов столбцов